summary: |
        This example presents a damage and loss assessment for buildings under wind and water inundation hazards from a hurricane. Approximately 6,600 buildings with various occupancy types and construction materials are considered in Atlantic City, NJ, with specified rulesets for determining key building characteristics.
        A Category 5 intensity hurricane with 3-s gust peak wind speeds, obtained from the Storm Hazard Projection Tool (NJCoast project), is employed with HAZUS-Hurricane wind fragility functions to estimate building damage states and loss ratios. The peak wind speeds are calculated using a linear analytical model for the boundary layer winds (Snaiki and Wu, 2017), and the peak inundation heights are calculated from a surrogate model (Jia and Taflanidis, 2013).
        
#<p>Tags: (Hurricane | IM as EDP | HAZUS building-level D&L)</p>
   

#Estimate damages and losses for a collection of buildings located in Atlantic City, NJ.
difficulty: 0
