summary: |
        This example presents a building loss assessment given a USGS ShakeMap as input. The Mw7.8 Scenario Earthquake - North San Andreas + North Coast + Peninsula + Santa Cruz Mountain (shakemap_id=npsanandreassansapsasm7p8_se) is employed in this example.
        Approximately 21,000 buildings are considered in the city of San Mateo, CA.

#<p>Tags: (ShakeMap | IM as EDP | HAZUS building-level D&L)<p>

difficulty: 1

