summary: |
  This example features a systematic regional seismic damage and loss assessment for Istanbul, Turkey. The ground motion acceleration time histories were simulated using the hercules software and a detailed geophysical model of Istanbul region ([ZhangEtAl2021]_). The ground motions are used to investigate the impact of a Mw7.0 earthquake on the Central Marmara Basin fault. Engineering Demand Parameters are simulated with OpenSees models for individual reinforced concrete buildings in this example. Building damage and loss is evaluated the story-level based on the HAZUS earthquake damage and loss assessment methodology.
 
#<p>Tags: (physics-based ground motions | OpenSees Building Response | CustomPy Simulation | HAZUS story-level D&L)</p>

#This example features a systematic regional seismic damage and loss assessment for Istanbul, Turkey.

difficulty: 1

