summary: |
  This example demonstrates the water distribution system performance assessment using REWET. REWET is a tool to assess the functionality of a Water Distribution System after any catastrophic event causing damage to the system. RWEET use a general restoration policy. The method is explained in Naeimi Dafchahi, S., & Davidson, R. A. (2023). Post-event restoration simulation of water distribution systems: a generally applicable approach. ProQuest Dissertations & Theses.

#<p>Tags: (IM field from PSHA | IM as EDP | HAZUS building-level D&L)<p>

difficulty: 1

